[package]
name = "kai-fansubs"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository = "https://github.com/sekiju/kai/tree/main/kai-fansubs"

[dependencies]
encoding_rs = "0.8"
reqwest.workspace = true
scraper = "0.25"
thiserror.workspace = true
tower.workspace = true
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }

[[example]]
name = "catalog"
path = "examples/catalog.rs"

[[example]]
name = "media"
path = "examples/media.rs"

[features]
serde = ["dep:serde"]
